### ISSUE TITLE
Convert markdown resources to Jekyll web pages

### ISSUE THREAD

**Issue by justwheel** [librecorps/resources#3]
# Summary

Create Jekyll website in GitHub Pages to provide an easy-to-navigate web interface 

# Background

Currently we are storing knowledge as markdown files in this git repo. This is easy for us to maintain and also gives us a fixed place to link out in other places. However, a simple Jekyll site would improve reader experience and hopefully give our content a more professional look-and-feel.

# Details

The scope for this should be small, to almost function as a small wiki. The main focus is to host written content that is most useful to LibreCorps team members, but could also be helpful as a resource for cohorts we work with. A secondary priority would be a broader, wider audience who may find this resources useful.

Also we need to choose a license, but I'll open a new issue for that.

# Outcome

* **3rd priority**: UX does not change for maintainers to add/edit/remove content (as markdown files with headers)
* **2nd priority**: Better experience/appearance for cohorts using our resources to inform their processes
* **1st priority**: _Possibly_ easier to attract publicity as a helpful resource in future outreach efforts

**Comment by Nolski** [comment]
I like this idea a lot. Currently, a lot of our work is in google docs (which certainly has its benefits) but if we're going to put resources on github, having them exist as part of a website would be much more useful.

I think in addition to the above, we should strictly define what goes in the resources, and what goes in our google drive as to avoid any confusion around where we should be putting what.

I think that perhaps any template or copy/pasteable resource should go in here provided it can easily be imported into a google docs document. Obviously, there are implications of google docs not being FOSS but I have yet to find a suitable alternative to do shared document editing on in real time.

### Themes?

Might be worthwhile to start off with a pre-existing jekyll theme and go from there? Happy to hear suggestions, I did a bit of looking around and there's quite a few nice ones that you can pay for. I'm not sure what github's support for [hugo](https://gohugo.io/) is but I found this really nice template which seems like it might support our needs

https://themes.gohugo.io/dot-hugo-documentation-theme/

**Comment by Nolski** [comment]
I took a quick shot at converting what we had over into a hugo site. Seemed fairly simple. I have a [working draft here](https://github.com/Nolski/example-librecorps-site) (simply for hosting purposes). Not much modification had to be made to our markdown files either which was nice. Simply deployed to a docs file.

You can find the deployed example below:

https://nolski.github.io/example-librecorps-site/

**Comment by Nolski** [comment]
Categories:
 - Legal
 - FOSS Community Strategy
 - Product management
 - AI Ethics
 - Outreach & Marketing
 - Tooling & Automation

**Comment by justwheel** [comment]
So, @Nolski effectively did this in #5. Since #5 is merged and we are now using Hugo to build static content on the site, I'm closing this as complete. :clapper:
