### ISSUE TITLE
Choose a Creative Commons license for content

### ISSUE THREAD

**Issue by justwheel** [librecorps/resources#4]
# Summary

Choose a license to make our written content more free

# Background

Our notes and written resources do not have a license. Therefore, by default they fall under individual copyright. The [Creative Commons licenses](https://creativecommons.org/) are good picks for creating and sharing knowledge works.

# Details

I suggest the [CC Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/). This license permits changes to be made to our work and reshared provided the remixed content is licensed the same. It also forbids commercial use of this work without prior permission. I felt like this was a useful protection of our work since we are publishing this freely and also working with large commercial entities via LibreCorps.

# Outcome

Easier for others to read, use, change, and redistribute our content under a mostly-free license

**Comment by Nolski** [comment]
@jwflory we might be in violation of the "non-comercial" aspect of your suggested license as UNICEF is paying us to distribute these resources to the various IF teams... Right?

**Comment by Nolski** [comment]
As per @jwflory's comment in IRC

>  I'll add this to the issue, but as licensors, we can still choose how to reshare our works in some commercial cases: https://wiki.creativecommons.org/wiki/NonCommercial_interpretation

I'm going to +1 on the non commercial license.

**Comment by justwheel** [comment]
See #6 to close this issue.
